config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :layers
  resources :fields
  resources :row_contents
  get "/layers/:id/schema" => "layers#schema"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :departement
end

app/models/departement.rb
class Departement < ApplicationRecord
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :layer
  enum enum_field_type: {text: :text, float: :float, integer: :integer}
  validates :field_type, inclusion: {in: enum_field_types.keys}

  after_create_commit -> do
    broadcast_append_to layer, target: "fields"
    broadcast_before_to layer, target: "delete-column", partial: "fields/th"
    layer.row_contents.each do |row_content|
      target = [row_content.id, "action"].join("-")
      broadcast_before_to layer, target: target, partial: "fields/field_in_form", locals: {field: self, form: row_content.id, value: nil}
    end
  end

  after_destroy_commit -> do
    broadcast_remove_to layer
    Turbo::StreamsChannel.broadcast_remove_to layer, targets: ".field-#{id}"
  end

  def geometry_type
    layer.geometry_type
  end

  def numerical?
    ["float", "integer"].include?(field_type)
  end
end

app/models/layer.rb
class Layer < ApplicationRecord
  has_many :fields, dependent: :delete_all
  has_many :row_contents, dependent: :delete_all
  enum enum_geometry_type: {point: :point, linestring: :linestring, polygon: :polygon}
  validates :geometry_type, inclusion: {in: enum_geometry_types.keys}
end

app/models/row_content.rb
class RowContent < ApplicationRecord
  belongs_to :layer
  after_update_commit -> { broadcast_replace_to layer }
  after_destroy_commit -> { broadcast_remove_to layer }
  after_create_commit -> { broadcast_append_to layer, target: "rows-tbody", partial: "row_contents/row_content", locals: {row_content: self} }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: %i[show edit update destroy]

  def new
    @field = Field.new
  end

  def edit
  end

  def update
    if @field.update(field_params)
      redirect_to @field, notice: "Field was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @layer = Layer.find(field_params[:layer_id])
    @field = @layer.fields.create(field_params)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @field.layer }
    end
  end

  def destroy
    @field.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @field.layer, notice: "Field was successfully destroyed." }
    end
  end

  private

  def set_field
    @field = Field.find(params[:id])
  end

  def field_params
    params.require(:field).permit(:label, :layer_id, :field_type)
  end
end

app/controllers/layers_controller.rb
require "securerandom"

class LayersController < ApplicationController
  before_action :set_layer, only: %i[show edit update destroy schema]

  def index
    @layers = Layer.all
  end

  def show
  end

  def new
    @layer = Layer.new
  end

  def edit
    # Every time we open a new tab, we create this session id
    # It allows to keep track what
    @session_id = SecureRandom.alphanumeric
  end

  def update
    if @layer.update(layer_params)
      redirect_to @layer, notice: "Layer was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @layer = Layer.new(layer_params)
    if @layer.save
      redirect_to @layer
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      render "new"
    end
  end

  def destroy
    @layer.destroy
    redirect_to layers_url, notice: "Layer was successfully destroyed."
  end

  def schema
    properties = @layer.fields.all.map { |f| field_schema(f) }.to_h

    render json: {
      type: :object,
      properties: properties
    }.to_json
  end

  private

  def set_layer
    @layer = Layer.find(params[:id])
  end

  def layer_params
    params.require(:layer).permit(:name, :geometry_type)
  end

  def field_schema(field)
    mapping = {
      "text" => :string,
      "float" => :number,
      "integer" => :integer
    }

    [field.id, type: mapping[field.field_type], title: field.label]
  end
end

app/controllers/row_contents_controller.rb
class RowContentsController < ApplicationController
  before_action :set_layer, only: %i[create new]
  before_action :set_row_content, only: %i[destroy update]

  def new
    @row_content = @layer.row_contents.new
    # The form is filled by someone that shouldn’t be redirected to the main page
    @anonymous = true
    @values = {}
  end

  def edit
    @row_content = RowContents.find(params[:id])
    @layer = @row_content.layer
    @values = @row_content.values
  end

  def create
    point = params.require(:row_content).permit(:longitude, :latitude, :layer_id, :anonymous)

    @row_content = @layer.row_contents.create({
      layer: @layer,
      point: RGEO_FACTORY.point(point[:longitude], point[:latitude]),
      values: fields(@layer)
    })

    if point[:anonymous] == "true"
      redirect_to action: :edit, id: @row_content
    else
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @row_content.layer }
      end
    end
  end

  def destroy
    @row_content.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @row_content.layer, notice: "Geometry was successfully destroyed." }
    end
  end

  def update
    @row_content.update(values: fields(@row_content.layer))
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @row_content.layer, notice: "Geometry properties were successfully updated." }
    end
  end

  private

  def set_row_content
    @row_content = RowContent.find(params[:id])
    puts @row_content
  end

  def fields(layer)
    field_keys = layer.fields.map { |field| field.id }
    params.require(:row_content).permit(field_keys)
  end

  def set_layer
    layer_id = params[:layer_id] || params[:row_content][:layer_id]
    @layer = Layer.find(layer_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fields/_field.html.erb
<li id="<%= dom_id(field) %>">
    <div>
        <span><%= field.label %> (<%= field.field_type %>)</span>
    <%= button_to field, method: :delete, form_class: "level-item" do %>
        <span>delete</span>
    <% end %>
</li>

app/views/fields/_field_in_form.html.erb
<td class="field field-<%= field.id %> <%= "numerical" if field.numerical? %>">
  <% if ["float", "integer"].include?(field.field_type) then %>
    <%= number_field_tag "row_content[#{field.id}]", nil, id: field.id, class: "input", value: value, data: {action: "row#setModified focusin->row#focusIn"}, form: form %>
  <% else %>
    <%= text_field_tag "row_content[#{field.id}]", nil, id: field.id, class: "input", value: value, data: {action: "row#setModified focusin->row#focusIn"}, form: form %>
  <% end %>
</td>

app/views/fields/_form.html.erb
<%= form_with model: Field.new, data: {action: "dropdown#toggle"} do |form| %>
  <%= form.hidden_field :layer_id, value: @layer.id %>
  <div>
    <%= form.label "Field label", class: "label" %>
    <%= form.text_field :label, class: "input" %>
  </div>

  <div>
    <%= form.label "Field name" %>
    <div>
      <%= form.collection_radio_buttons(:field_type, Field.enum_field_types.keys, :to_s, :titlecase) do |b| %>
        <%= b.label(class: "radio") do %>
          <%= b.text %>
          <%= b.radio_button %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fields/_th.html.erb
<th class="field-<%= field.id %>">
    <div class="dropdown" data-controller="dropdown">
        <button aria-haspopup="true" aria-controls="dropdown-menu" data-action="click->dropdown#toggle">
            <span><%= field.label %></span>
            <span>↓</span>
        </button>
        <div class="dropdown-content" role="menu">
            <%= button_to field, method: :delete, form_class: "level-item" do %>
                <span>Delete column</span>
            <% end %>
        </div>
    </div>
</th>

app/views/layers/_form.html.erb
<%= form_with(model: layer) do |form| %>
  <% if layer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(layer.errors.count, "error") %> prohibited this layer from being saved:</h2>

      <ul>
        <% layer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Layer name" %>
    <%= form.text_field :name %>
  </div>

  <div class="field radio">
    <h3>Geometry type</h3>
    <%= form.collection_radio_buttons :geometry_type, Layer.enum_geometry_types.keys, :to_s, :titlecase %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layers/edit.html.erb
<%= turbo_stream_from @layer %>
<nav role="navigation" aria-label="main navigation">
    <div>
      <%= link_to "Ĝis", "/layers", class: "navbar-item" %>
    </div>
    <div>
      <%= text_field :user_name, nil, data: {map_target: "userName"}, placeholder: "your name" %>
      <%= hidden_field_tag :session_id, @session_id, data: {map_target: "sessionId"} %>
      <%= hidden_field_tag :layer_id, @layer.id, data: {map_target: "layerId"} %>
    </div>
    <div>
      <%= form_with(model: @layer) do |form| %>
        <%= form.text_field :name %>
      <% end %>
    </div>
</nav>
<div id="layer_edit" data-controller="map">
    <div id="data_editor" id="data-editor">
        <%= render "row_contents/table" %>
    </div>
    <div id="map" data-map-target="map">
        <%= render "row_contents/new", layer: @layer %>
    </div>
</div>

app/views/layers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Layers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @layers.each do |layer| %>
      <tr>
        <td><%= layer.name %></td>
        <td><%= link_to 'Show', layer %></td>
        <td><%= link_to 'Edit', edit_layer_path(layer) %></td>
        <td><%= button_to 'Destroy', layer, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Layer', new_layer_path %>

app/views/layers/new.html.erb
<h1>New Layer</h1>

<%= render 'form', layer: @layer %>

<%= link_to 'Back', layers_path %>

app/views/layers/show.html.erb
<p id="notice"><%= notice %></p>
<div>
    <h2>Layer <%= @layer.name %></h2>
    Type: <%= @layer.geometry_type %>
    <h3>Fields</h2>
    <ul>
    <% @layer.fields.each do |field| %>
        <li> <%= render field %> </li>
    <% end %>
    </ul>
</div>

<%= link_to 'Edit', edit_layer_path(@layer) %> |
<%= link_to 'Back', layers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ĝis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href='https://unpkg.com/maplibre-gl@2.1.7/dist/maplibre-gl.css' rel='stylesheet' />
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "/mvp.css", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/row_contents/_form.html.erb
<%= form_with model: @row do |form| %>
    <%= form.hidden_field :layer_id, value: @layer.id %>
    <%= form.hidden_field :anonymous, value: "true" if @anonymous %>
    <% @layer.fields.each do |field| %>
        <div>
            <%= form.label field.id, field.label  %>
            <div>
                <%= form.text_field field.id, value: @values[field.id] %>
            </div>
        </div>
    <% end %>
    <div>
        <%= form.submit "Sauvegarder" %>
    </div>
<% end %>

app/views/row_contents/_new.html.erb
<%= form_with model: RowContent.new, data: {"map-target" => "newPointForm"}, class: "is-hidden" do |form| %>
  <%= form.hidden_field :layer_id, value: layer.id %>
  <%= form.hidden_field :longitude, data: {"map-target" => "longitudeField"} %>
  <%= form.hidden_field :latitude, data: {"map-target" => "latitudeField"} %>
  <%= form.submit %>
<% end %>

app/views/row_contents/_point.html.erb
<tr id="<%= dom_id(@row) %>"
    data-map-target="point"
    data-lng="<%= row_content.point.geog.x %>"
    data-lat="<%= row_content.point.geog.y %>"
    data-controller="row"
    data-action="focusout->row#focusOut"
>
    <%= yield %>
</tr>

app/views/row_contents/_row_content.html.erb
<tr id="<%= dom_id(row_content) %>"
    data-map-target="point"
    data-lng="<%= row_content.point.x %>"
    data-lat="<%= row_content.point.y %>"
    data-controller="row"
    data-action="focusout->row#focusOut"
>
    <% row_content.layer.fields.each do |field| %>
        <%= render partial: "fields/field_in_form", locals: {field: field, value: row_content.values[field.id], form: row_content.id} %>
    <% end %>
    <td id="<%= row_content.id %>-action">
        <div class="actions">
            <%= form_with method: :patch, model: row_content, id: row_content.id, data: {"row-target": "form"} do |form| %>
                <%= form.button method: :update, disabled: true, data: {"row-target": "save", "action": "row#setLoading"} do %>
                    Save
                <% end %>
            <% end %>
            <%= button_to row_content, method: :delete do %>
                Delete
            <% end %>
        </div>
    </td>
</tr>

app/views/row_contents/_table.erb
<table>
    <thead>
        <tr>
            <%= render partial: "fields/th", collection: @layer.fields, as: :field %>
            <th id="delete-column" class="row-actions">
                <div class="dropdown" data-controller="dropdown">
                  <button aria-haspopup="true" aria-controls="dropdown-menu"  data-action="click->dropdown#toggle">
                    <span>+</span>
                  </button>
                  <div class="dropdown-content" role="menu">
                      <%= render 'fields/form' %>
                  </div>
                </div>
            </th>
        </tr>
    </thead>
    <tbody id="rows-tbody">
      <%= render @layer.row_contents.order(:created_at) %>
    </tbody>
</table>

app/views/row_contents/edit.html.erb
<section class="section">
<div class="container">
    <h1>Modifier un formulaire</h1>
    <p>Cette restera accessible et partageable par <%= link_to "ce lien", edit_point_url(@point) %>
    <%= render 'form' %>
</div>
</section>

app/views/row_contents/new.html.erb
<section class="section">
<div class="container">
    <h1>Saisir un nouveau formulaire</h1>
    <p>
        Vous n’avez pas besoin de finir la saisie. En cliquant sur « Sauvegarder »,
        vous obtiendrez un lien pour poursuivre l’édition plus tard.
    </p>
    <%= render 'form' %>
</div>
</section>